"""Per-run companion files: the README and the manifest.

Both exist for the same reason. Output is split by cloud and by credential scope,
and for a region-scoped provider by region too, so a run over a real estate
produces tens or hundreds of files. Two consequences follow:

* **Instructions must be written once, not per file.** How to review the output,
  how to apply it, and what the tool does not do are properties of the run. A
  1 KB preamble repeated in 200 files was roughly a third of total output, for text
  a reader skips after the first time. It lives in ``README.md`` instead, and each
  artifact carries a short pointer plus the warnings that must reach someone who
  opens one file in isolation.
* **A directory of 200 files needs an index.** ``manifest.json`` records what each
  file covers -- including which cloud and which credential scope -- so choosing
  which to run is a query rather than a directory listing, and so a pipeline can
  drive the files without parsing shell or HCL.

Both are written once at the top of the output directory rather than once per
cloud, because the reconciliation they support is a property of the run: a reader
has to be able to see that a finding which produced no artifact was withheld or
unsupported, not lost. Splitting the index per cloud would make that unanswerable
from any single file.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass

from remgen import PROJECT_NAME
from remgen.core.layout import OutputUnit
from remgen.core.model import Recipe
from remgen.core.provider import Provider


@dataclass(frozen=True)
class RunCounts:
    """What became of every record read, at record granularity.

    Recorded because the manifest was otherwise a record of what *worked*: a run
    that rejected a third of its input was byte-indistinguishable, to any consumer,
    from a clean one. The counts print to stderr for a human, but stderr prose is
    not an interface -- a scheduler had nothing to branch on.

    These are the same numbers the console summary prints, and they reconcile the
    same way::

        records_read = usable_findings + rejected
        usable_findings = duplicates_merged + distinct_findings
        distinct_findings = remediated + withheld_by_safety_level + unsupported

    The identity is documented rather than enforced here. Every field is derived
    inside this tool from data it already holds, so a mismatch is a defect in the
    generator, and raising over it *after* the artifacts are rendered would abort a
    run whose files are correct in order to complain about its own bookkeeping. The
    reconciliation is asserted in the test suite instead, against real fixtures,
    which is where a generator's arithmetic error should surface.

    Note the one count that is deliberately *not* in this chain: the top-level
    ``remediations`` in the manifest sums ``files[].remediations``, and a resource
    fixed by both a script and an HCL block counts twice there -- that is what
    "remediation" means per file. Mixing it into a per-record chain is precisely the
    error this dataclass exists to prevent, so the two live under different names.

    Attributes:
        records_read: Every record the source handed over, usable or not.
        usable_findings: Records that parsed and validated.
        rejected: Records that could not be used at all.
        scope_conflicts: The subset of ``rejected`` that were well-formed but named
            a credential scope contradicting their own resource identifier. Broken
            out rather than merged, because these mean a mis-scoped export while the
            rest mean malformed data, and whoever fixes them looks in a different
            place. Always 0 for a cloud with no scope-conflict hook.
        duplicates_merged: Usable findings that collapsed into an earlier one.
        distinct_findings: Usable findings after deduplication.
        remediated: Distinct findings that produced output.
        withheld_by_safety_level: Distinct findings whose recipe exists but sits
            above the requested ``--safety-level``. Separate from ``unsupported``:
            this is coverage the tool has and declined to use, that is coverage it
            never had.
        unsupported: Distinct findings naming a policy with no curated recipe.
            Collapsing this into ``rejected`` would make partial catalog coverage
            look like malformed input.
    """

    records_read: int = 0
    usable_findings: int = 0
    rejected: int = 0
    scope_conflicts: int = 0
    duplicates_merged: int = 0
    distinct_findings: int = 0
    remediated: int = 0
    withheld_by_safety_level: int = 0
    unsupported: int = 0


_README = """\
# {display} remediation artifacts

Generated by {command} ({project}) v{version} on {generated_at}.

**These files modify {display} resources. Nothing has been applied.** {command}
only writes files; you review and run them.

## What these are

Remediations for {count} finding(s) across {scopes} {display} {scope_plural},
drawn from a curated recipe set in which every API call is individually verified
against {display}'s own published API definitions. Coverage is intentionally
partial: a policy is included only when its remediation is universally scriptable
and generally considered safe. Findings with no matching recipe were reported in
the run summary and are not here.

Best effort, not authoritative. The generator cannot see your resources' current
configuration, only the findings, so review remains necessary.

## Why there are several files, and several directories

Artifacts are grouped in a directory per cloud, and within it split one file per
{scope_noun} -- and for HCL one per region when that cloud's Terraform provider is
region-scoped. This is a correctness requirement, not tidiness: a shell script
invokes one vendor CLI using your shell's ambient credentials, and a Terraform
provider configuration covers one credential scope. A file that mixed them would
not merely be untidy; for HCL it could import a same-named resource from the wrong
{scope_noun}. Large scopes are additionally split into numbered parts for
reviewability.

**Each file must be run with credentials for the {scope_noun} named in its
filename.** The cloud and the {scope_noun} are both in every filename, so a file
stays self-describing after it is copied out of its directory. See
`manifest.json` for the full index.

## Review checklist

1. Confirm the resource identifiers are the ones you intend to change.
2. Read the safety notes above each policy group. Some changes are not reversible.
3. Confirm your credentials target the {scope_noun} named in the filename. The
   shell scripts verify this themselves and exit rather than touch the wrong one.
4. Run against one resource first.

## Applying: CLI scripts (`*{extension}`)

Requires {cli_requirement} and credentials with permission for the operations
listed.

```sh
bash ./{cloud}/remediate-{cloud}-<{scope_noun}>-<region>{extension}
```

Each script sets `set -euo pipefail`, so it stops at the first failure instead of
continuing with a broken assumption. Delete any command you disagree with and run
the rest -- the commands are independent by design.

## Applying: OpenTofu / Terraform (`*.tf`)

Requires OpenTofu >= 1.6 or Terraform >= 1.5 (for `import` block support) and the
provider version noted per policy group.

Each `import` block adopts an existing {display} resource into state; its paired
`resource` block declares the corrected setting. Both are required: a `resource`
block alone would try to create a duplicate rather than fix what exists.

1. Place the file in the workspace that should own those resources, or configure a
   standalone provider using the commented block in the file's header.
2. Complete every `# TODO`. They mark arguments the provider requires that a
   finding cannot supply. The placeholder values satisfy type checking so the file
   validates as generated -- they are **not** the resources' real values.
3. `tofu plan` must report "N to import, 0 to add, 0 to destroy". Any "to add"
   means an import identifier is wrong. Do not apply.
4. Apply only when the plan matches your expectation.

Do not import a resource that another workspace already manages. Change the
attribute in the configuration that already owns it instead.

## After applying

Re-scan in Tenable Cloud Security to confirm the findings clear.

## Policy reference

Every policy represented in this run, with what its remediation does and what to
watch for. The artifacts carry each policy's safety notes inline -- reversibility,
cost, and traffic impact are stated where the commands are. This section holds the
reference detail that is identical for every occurrence, so it is stated once here
rather than repeated in each file.

{policy_reference}
"""

_POLICY_ENTRY = """\
### {title}

- **Policy ID:** `{policy_id}`
- **Safety tier:** {tier}
- **Remediations in this run:** {count}
- **API:** `{service}.{operation}`
{hcl_line}
{summary}
{critical}{safety}{prerequisites}{caveats}{docs}
"""


def _bullets(heading: str, items: tuple[str, ...]) -> str:
    if not items:
        return ""
    lines = "\n".join(f"- {item}" for item in items)
    return f"\n**{heading}**\n\n{lines}\n"


def _policy_reference(units: list[OutputUnit]) -> str:
    """Render the per-policy reference section, one entry per distinct policy."""
    seen: dict[str, tuple[Recipe, int]] = {}
    for unit in units:
        for recipe, _finding in unit.pairs:
            existing = seen.get(recipe.policy_id)
            seen[recipe.policy_id] = (recipe, (existing[1] if existing else 0) + 1)

    entries = []
    for recipe, count in sorted(
        seen.values(), key=lambda rc: (rc[0].safety_tier.value, rc[0].policy_title)
    ):
        hcl_line = (
            f"- **IaC resource:** `{recipe.hcl.resource_type}` "
            f"(provider >= {recipe.hcl.min_provider_version})\n"
            if recipe.hcl is not None
            else "- **IaC resource:** none; this policy is CLI only\n"
        )
        entries.append(
            _POLICY_ENTRY.format(
                title=recipe.policy_title,
                policy_id=recipe.policy_id,
                tier=recipe.safety_tier.value,
                # Counted across formats, so a resource fixed by both a script and
                # an HCL block counts twice -- which is what "remediations" means
                # here. The finding count is in the run summary.
                count=count,
                service=recipe.api.service,
                operation=recipe.api.operation,
                hcl_line=hcl_line,
                summary=f"\n{recipe.summary}\n",
                # First, and above Safety. A critical caveat is by definition the
                # consequence the derived safety notes cannot state, so listing it
                # after them buries the only line the tier fields could not warn
                # about. It is also emitted inline in the artifacts; this entry is
                # the full text, since the artifacts carry it wrapped to a comment.
                critical=_bullets("Read before applying", recipe.critical_caveats),
                safety=_bullets("Safety", recipe.safety_notes),
                prerequisites=_bullets("Prerequisites", recipe.prerequisites),
                caveats=_bullets("Caveats", recipe.caveats),
                docs=f"\n[Documentation]({recipe.docs_url})\n" if recipe.docs_url else "",
            )
        )
    return "\n".join(entries)


def render_readme(
    units: list[OutputUnit],
    *,
    provider: Provider,
    version: str,
    generated_at: str,
    count: int,
) -> str:
    """Render the per-run README that the artifacts point at.

    Takes the whole :class:`~remgen.core.provider.Provider` rather than five
    separate strings. The README is prose *about* one cloud -- its name, its word
    for a credential scope, its CLI and its version requirement all appear in it --
    and a caller that could supply four of the five consistently and the fifth from
    somewhere else is a caller that can produce a document describing no real cloud.

    Args:
        units: Every output unit written this run. One command covers one cloud, so
            these share a cloud; the assertion below states that rather than
            trusting it.
        provider: The cloud these artifacts target.
        version: Tool version.
        generated_at: ISO-8601 timestamp, supplied so this stays deterministic.
        count: Number of remediations, for the summary line.

    Raises:
        ValueError: If ``units`` span more than one cloud, or a cloud other than
            ``provider``'s. Every cloud-specific sentence below would then be wrong
            for some of the files the document indexes, which is worse than no
            document -- a reader would follow AWS instructions for an Azure file.
    """
    clouds = {unit.cloud for unit in units}
    if clouds - {provider.cloud}:
        raise ValueError(
            f"render_readme describes one cloud, but got units for "
            f"{sorted(clouds)} under provider {provider.cloud!r}"
        )

    noun = provider.credential_scope_noun
    plural = noun if noun.endswith("s") else f"{noun}s"
    return _README.format(
        command=provider.command,
        display=provider.display_name,
        cloud=provider.cloud,
        project=PROJECT_NAME,
        version=version,
        generated_at=generated_at,
        count=count,
        scopes=len({unit.scope_id for unit in units}),
        scope_noun=noun,
        scope_plural=plural,
        extension=provider.shell_extension,
        cli_requirement=provider.cli_requirement or f"the {provider.display_name} CLI",
        policy_reference=_policy_reference(units),
    )


def render_manifest(
    units: list[OutputUnit],
    *,
    version: str,
    generated_at: str,
    command: str = "remgen",
    counts: RunCounts | None = None,
) -> str:
    """Render a machine-readable index of the generated files.

    Emitted so a pipeline can select and drive files by scope without parsing shell
    or HCL, and so an operator can answer "which file covers account X" without
    opening any of them. The per-policy counts make the run auditable after the
    fact: what was proposed, where, and under which safety tier.

    Each entry's ``path`` is relative to the output directory and includes the
    cloud segment, so a consumer can open the file without reconstructing the
    layout rule. ``file`` is kept alongside it as the bare name, because selecting
    by name is the common case and re-deriving it from the path is the kind of
    string manipulation that gets it wrong once.

    Args:
        counts: What became of every record read -- see :class:`RunCounts`. Written
            in full even when every field is zero, so an absent ``input`` block means
            an older generator rather than a run with nothing to report. Defaults to
            all-zero rather than being required, because this function is also called
            from tests and from callers that only want the file index; a caller that
            omits it gets a manifest that claims nothing, not one that lies.
    """
    # Policy detail is declared once in a top-level map and referenced by id per
    # file. Inlining title and tier into every file entry repeated them once per
    # (file x policy) pair, which for a large estate was most of the manifest.
    policies: dict[str, dict[str, object]] = {}
    entries = []
    for unit in units:
        # Named `per_policy`, not `counts`: it used to be `counts`, which shadowed the
        # `counts` parameter and left the run's own numbers replaced by the last unit's
        # policy tally by the time the payload was built.
        per_policy: dict[str, int] = {}
        for recipe, _finding in unit.pairs:
            per_policy[recipe.policy_id] = per_policy.get(recipe.policy_id, 0) + 1
            if recipe.policy_id not in policies:
                policies[recipe.policy_id] = {
                    "title": recipe.policy_title,
                    "safety_tier": recipe.safety_tier.value,
                    "api": f"{recipe.api.service}.{recipe.api.operation}",
                    "reversible": recipe.reversible,
                    "hcl_resource_type": (
                        recipe.hcl.resource_type if recipe.hcl is not None else None
                    ),
                }
        entries.append(
            {
                "file": unit.filename,
                "path": unit.relative_path,
                "cloud": unit.cloud,
                "format": unit.fmt.value,
                # The credential scope, under a cloud-neutral key. The cloud's own
                # word for it is in "scope_noun" rather than being the key name, so
                # a consumer reads one field across every cloud instead of probing
                # for "account_id" or "subscription_id".
                "scope_id": unit.scope_id,
                "scope_noun": unit.scope_noun,
                # null rather than a placeholder: the field means "this file spans
                # regions", which is a real state for a CLI script.
                "region": unit.region,
                "part": unit.part,
                "total_parts": unit.total_parts,
                "remediations": len(unit.pairs),
                # policy id -> resource count. Look the id up in "policies".
                "policy_counts": dict(sorted(per_policy.items())),
            }
        )

    payload = {
        "generator": f"{command} ({PROJECT_NAME})",
        "version": version,
        "generated_at": generated_at,
        "applied": False,
        "notes": (
            "Each file targets one cloud and one credential scope (and one region "
            "where that cloud's Terraform provider is region-scoped), and must be run "
            "with credentials for it. Nothing here has been applied."
        ),
        "clouds": sorted({unit.cloud for unit in units}),
        "scopes": sorted({unit.scope_id for unit in units}),
        # Total across the files below, so a resource fixed by both a script and an
        # HCL block counts twice -- the same sense as `files[].remediations`. The
        # per-record accounting is in "input", which is a different scale on purpose.
        "remediations": sum(len(unit.pairs) for unit in units),
        # What became of every record read, including what did NOT make it into the
        # files below. See `RunCounts` for the reconciliation identity.
        "input": asdict(counts or RunCounts()),
        "policies": dict(sorted(policies.items())),
        "files": entries,
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


__all__ = ["RunCounts", "render_manifest", "render_readme"]
