"""Per-run companion files: the README and the manifest.

Both exist for the same reason. Output is split by account, and for HCL by region,
so a run over a real estate produces tens or hundreds of files. Two consequences
follow:

* **Instructions must be written once, not per file.** How to review the output,
  how to apply it, and what the tool does not do are properties of the run. A
  1 KB preamble repeated in 200 files was roughly a third of total output, for text
  a reader skips after the first time. It lives in ``README.md`` instead, and each
  artifact carries a short pointer plus the warnings that must reach someone who
  opens one file in isolation.
* **A directory of 200 files needs an index.** ``manifest.json`` records what each
  file covers, so choosing which to run is a query rather than a directory listing,
  and so a pipeline can drive the files without parsing shell or HCL.
"""

from __future__ import annotations

import json

from remgen.layout import OutputUnit
from remgen.model import Recipe

_README = """\
# AWS remediation artifacts

Generated by remgen (curated-aws-remediation-generator) v{version} on {generated_at}.

**These files modify AWS resources. Nothing has been applied.** remgen only writes
files; you review and run them.

## What these are

Remediations for {count} finding(s) across {accounts} AWS account(s), drawn from a
curated recipe set in which every AWS API call is individually verified against the
shipped AWS service models. Coverage is intentionally partial: a policy is included
only when its remediation is universally scriptable and generally considered safe.
Findings with no matching recipe were reported in the run summary and are not here.

Best effort, not authoritative. The generator cannot see your resources' current
configuration, only the findings, so review remains necessary.

## Why there are several files

One file per AWS account, and for HCL one per region, because neither format can
target more than one account at a time -- a shell script uses your shell's ambient
credentials, and an AWS provider is scoped to one account and region. A file that
mixed them would not merely be untidy; for HCL it could import a same-named resource
from the wrong account. Large scopes are additionally split into numbered parts for
reviewability.

**Each file must be run with credentials for the account named in its filename.**
See `manifest.json` for the full index.

## Review checklist

1. Confirm the resource identifiers are the ones you intend to change.
2. Read the safety notes above each policy group. Some changes are not reversible.
3. Confirm your credentials target the account named in the filename. The shell
   scripts verify this themselves and exit rather than touch the wrong account.
4. Run against one resource first.

## Applying: aws CLI (`*.sh`)

Requires AWS CLI v2 and credentials with permission for the operations listed.

```sh
export AWS_PROFILE=your-profile-for-<account-id>
bash ./remediate-<account-id>-<region>.sh
```

Each script sets `set -euo pipefail`, so it stops at the first failure instead of
continuing with a broken assumption. Delete any command you disagree with and run
the rest -- the commands are independent by design.

## Applying: OpenTofu / Terraform (`*.tf`)

Requires OpenTofu >= 1.6 or Terraform >= 1.5 (for `import` block support) and the
AWS provider version noted per policy group.

Each `import` block adopts an existing AWS resource into state; its paired
`resource` block declares the corrected setting. Both are required: a `resource`
block alone would try to create a duplicate rather than fix what exists.

1. Place the file in the workspace that should own those resources, or configure a
   standalone provider using the commented block in the file's header.
2. Complete every `# TODO`. They mark arguments the provider requires that a
   finding cannot supply. The placeholder values satisfy type checking so the file
   validates as generated -- they are **not** the resources' real values.
3. `tofu plan` must report "N to import, 0 to add, 0 to destroy". Any "to add"
   means an import identifier is wrong. Do not apply.
4. Apply only when the plan matches your expectation.

Do not import a resource that another workspace already manages. Change the
attribute in the configuration that already owns it instead.

## After applying

Re-scan in Tenable Cloud Security to confirm the findings clear.

## Policy reference

Every policy represented in this run, with what its remediation does and what to
watch for. The artifacts carry each policy's safety notes inline -- reversibility,
cost, and traffic impact are stated where the commands are. This section holds the
reference detail that is identical for every occurrence, so it is stated once here
rather than repeated in each file.

{policy_reference}
"""

_POLICY_ENTRY = """\
### {title}

- **Policy ID:** `{policy_id}`
- **Safety tier:** {tier}
- **Remediations in this run:** {count}
- **AWS API:** `{service}.{operation}`
{hcl_line}
{summary}
{safety}{prerequisites}{caveats}{docs}
"""


def _bullets(heading: str, items: tuple[str, ...]) -> str:
    if not items:
        return ""
    lines = "\n".join(f"- {item}" for item in items)
    return f"\n**{heading}**\n\n{lines}\n"


def _policy_reference(units: list[OutputUnit]) -> str:
    """Render the per-policy reference section, one entry per distinct policy."""
    seen: dict[str, tuple[Recipe, int]] = {}
    for unit in units:
        for recipe, _finding in unit.pairs:
            existing = seen.get(recipe.policy_id)
            seen[recipe.policy_id] = (recipe, (existing[1] if existing else 0) + 1)

    entries = []
    for recipe, count in sorted(
        seen.values(), key=lambda rc: (rc[0].safety_tier.value, rc[0].policy_title)
    ):
        hcl_line = (
            f"- **IaC resource:** `{recipe.hcl.resource_type}` "
            f"(AWS provider >= {recipe.hcl.min_provider_version})\n"
            if recipe.hcl is not None
            else "- **IaC resource:** none; this policy is aws-CLI only\n"
        )
        entries.append(
            _POLICY_ENTRY.format(
                title=recipe.policy_title,
                policy_id=recipe.policy_id,
                tier=recipe.safety_tier.value,
                # Counted across formats, so a resource fixed by both a script and
                # an HCL block counts twice -- which is what "remediations" means
                # here. The finding count is in the run summary.
                count=count,
                service=recipe.api.service,
                operation=recipe.api.operation,
                hcl_line=hcl_line,
                summary=f"\n{recipe.summary}\n",
                safety=_bullets("Safety", recipe.safety_notes),
                prerequisites=_bullets("Prerequisites", recipe.prerequisites),
                caveats=_bullets("Caveats", recipe.caveats),
                docs=f"\n[AWS documentation]({recipe.docs_url})\n" if recipe.docs_url else "",
            )
        )
    return "\n".join(entries)


def render_readme(
    units: list[OutputUnit], *, version: str, generated_at: str, count: int
) -> str:
    """Render the per-run README that the artifacts point at."""
    accounts = len({unit.account_id for unit in units})
    return _README.format(
        version=version,
        generated_at=generated_at,
        count=count,
        accounts=accounts,
        policy_reference=_policy_reference(units),
    )


def render_manifest(
    units: list[OutputUnit], *, version: str, generated_at: str
) -> str:
    """Render a machine-readable index of the generated files.

    Emitted so a pipeline can select and drive files by scope without parsing shell
    or HCL, and so an operator can answer "which file covers account X" without
    opening any of them. The per-policy counts make the run auditable after the
    fact: what was proposed, where, and under which safety tier.
    """
    # Policy detail is declared once in a top-level map and referenced by id per
    # file. Inlining title and tier into every file entry repeated them once per
    # (file x policy) pair, which for a large estate was most of the manifest.
    policies: dict[str, dict[str, object]] = {}
    entries = []
    for unit in units:
        counts: dict[str, int] = {}
        for recipe, _finding in unit.pairs:
            counts[recipe.policy_id] = counts.get(recipe.policy_id, 0) + 1
            if recipe.policy_id not in policies:
                policies[recipe.policy_id] = {
                    "title": recipe.policy_title,
                    "safety_tier": recipe.safety_tier.value,
                    "api": f"{recipe.api.service}.{recipe.api.operation}",
                    "reversible": recipe.reversible,
                    "hcl_resource_type": (
                        recipe.hcl.resource_type if recipe.hcl is not None else None
                    ),
                }
        entries.append(
            {
                "file": unit.filename,
                "format": unit.fmt.value,
                "account_id": unit.account_id,
                # null rather than a placeholder: the field means "this file spans
                # regions", which is a real state for a CLI script.
                "region": unit.region,
                "part": unit.part,
                "total_parts": unit.total_parts,
                "remediations": len(unit.pairs),
                # policy id -> resource count. Look the id up in "policies".
                "policy_counts": dict(sorted(counts.items())),
            }
        )

    payload = {
        "generator": "remgen (curated-aws-remediation-generator)",
        "version": version,
        "generated_at": generated_at,
        "applied": False,
        "notes": (
            "Each file targets one AWS account (HCL: one account and region) and must "
            "be run with credentials for it. Nothing here has been applied to AWS."
        ),
        "accounts": sorted({unit.account_id for unit in units}),
        "policies": dict(sorted(policies.items())),
        "files": entries,
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


__all__ = ["render_manifest", "render_readme"]
