#!/usr/bin/env bash
#
# Generated by azremgen (curated-cloud-remediation-generator) v0.2.1
# Generated: 2026-08-07T19:36:15+00:00
#
# THIS SCRIPT MODIFIES AZURE RESOURCES. Review it before running it. Remediations
# come from a curated, individually verified recipe set; coverage is intentionally
# partial. See README.md in this directory for the review checklist.
#
# Requires: Azure CLI (az) 2.50 or later, and credentials that can reach the subscription below.
#
# shellcheck disable=SC2086
set -euo pipefail

if ! command -v az >/dev/null 2>&1; then
  echo "error: the 'az' CLI is not on PATH." >&2
  exit 1
fi
#
# Scope: azure subscription d27e6b04-93a1-4f58-8c7d-31fb9e2a604c, all regions
# Remediations in this file: 1
#
# Every command below names this subscription explicitly. The guard below confirms you
# can reach it before making any change.

# Subscription guard. Every command below names --subscription explicitly, so this
# does NOT require the subscription to be your active one -- it checks you can reach
# it at all, and fails before any change if you cannot.
#
# Note for readers familiar with the AWS script: that one refuses to run when the
# active account differs. This one does not, because an Azure login legitimately
# spans subscriptions and the target here is stated per command rather than
# inherited from the shell.
expected_subscription="d27e6b04-93a1-4f58-8c7d-31fb9e2a604c"
if ! az account show >/dev/null 2>&1; then
  echo "error: not logged in to Azure. Run 'az login' and re-run." >&2
  exit 1
fi
reachable="$(az account list --query "length([?id=='$expected_subscription'])" --output tsv)"
if [[ "$reachable" != "1" ]]; then
  echo "error: subscription $expected_subscription is not available to these" >&2
  echo "       credentials. These remediations are for that subscription only." >&2
  echo "       Run 'az login' with an identity that can reach it, or" >&2
  echo "       'az account set --subscription $expected_subscription' if you" >&2
  echo "       expected it to be present." >&2
  exit 1
fi
active_subscription="$(az account show --query id --output tsv)"
if [[ "$active_subscription" != "$expected_subscription" ]]; then
  echo "note: your active subscription is $active_subscription, but every command"
  echo "      below targets $expected_subscription explicitly. Proceeding."
fi
echo "Subscription $expected_subscription confirmed. Scope: azure subscription d27e6b04-93a1-4f58-8c7d-31fb9e2a604c, all regions"

# ==========================================================================
# SAFEST -- reversible, no data-path impact, no usage-scaled cost
# ==========================================================================

# POLICY: Storage Account in transit is not enabled
# Policy ID: bed905d4-758c-4698-9ed8-4cdd4271eb4e
# Resources: 1
#
# Reversible: az storage account update --ids <resource-id> --https-only false
# Summary, caveats and docs: see README.md

# /subscriptions/d27e6b04-93a1-4f58-8c7d-31fb9e2a604c/resourceGroups/rg-sandbox/providers/Microsoft.Storage/storageAccounts/acmesandboxdata
# (eastus)
echo ">> Storage Account in transit is not enabled :: /subscriptions/d27e6b04-93a1-4f58-8c7d-31fb9e2a604c/resourceGroups/rg-sandbox/providers/Microsoft.Storage/storageAccounts/acmesandboxdata"
az storage account update --ids /subscriptions/d27e6b04-93a1-4f58-8c7d-31fb9e2a604c/resourceGroups/rg-sandbox/providers/Microsoft.Storage/storageAccounts/acmesandboxdata --https-only true --subscription d27e6b04-93a1-4f58-8c7d-31fb9e2a604c

echo
echo "Done. 1 remediation command(s) completed."
echo "Re-scan in Tenable Cloud Security to confirm the findings clear."
