# Generated by azremgen (curated-cloud-remediation-generator) v0.2.1
# Generated: 2026-08-09T19:57:48+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# PROVIDER VERSION
#
# Verified against hashicorp/azurerm 5.x. The upper bound is deliberate: a
# provider major relocates arguments between resources -- aws v5 to v6 moved the
# `aws_s3_bucket` sub-arguments -- so an unbounded constraint would resolve to a
# major these blocks were never checked against, and fail in your workspace rather
# than in this project's CI.
#
# Commented for the same reason as the provider block below: a module may have only
# one `required_providers` configuration, and dropping a second one into an existing
# workspace is an error at `init`. Uncomment for standalone use.
#
# terraform {
#   required_providers {
#     azurerm = {
#       source  = "hashicorp/azurerm"
#       version = ">= 5.0, < 6.0"
#     }
#   }
# }
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# SCOPE: azure subscription d27e6b04-93a1-4f58-8c7d-31fb9e2a604c, all regions
#
# This file covers ONE subscription, because that is all an azurerm provider
# configuration covers. It may span locations: an azurerm provider block carries
# no location, so each resource names its own.
#
# CONFIRM the provider in this workspace targets subscription
# d27e6b04-93a1-4f58-8c7d-31fb9e2a604c. Unlike the AWS provider, azurerm has no
# `allowed_account_ids` equivalent -- `subscription_id` selects a subscription, it
# does not assert which one is acceptable, so a wrong value is not rejected. The
# import ids below are fully-qualified ARM ids that name this subscription, so a
# mismatch fails to find the resource rather than modifying the wrong one; expect
# "resource not found" if the provider is pointed elsewhere.
#
# Standalone use: uncomment this block.
#
# provider "azurerm" {
#   subscription_id = "d27e6b04-93a1-4f58-8c7d-31fb9e2a604c"
#   features {}
# }
# ---------------------------------------------------------------------------

# TODO: 1 of 1 resource block(s) below need values completed before applying.

# ==========================================================================
# Safety tier: SAFEST
# ==========================================================================

# POLICY: Storage Account in transit is not enabled
# Policy ID: bed905d4-758c-4698-9ed8-4cdd4271eb4e
#
# !! Any client still connecting over plain HTTP will fail after this change. That
#    traffic is unencrypted today, which is the finding -- but confirm no legacy client
#    depends on it before applying fleet-wide.
#
# Reversible: az storage account update --ids <resource-id> --https-only false
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires name, resource_group_name, location, account_tier,
# account_replication_type, which a finding cannot supply. The TODO placeholders below
# satisfy type checking only -- replace each with the resource's real value, or the
# import will reconfigure the resource incorrectly.
# Resources below: 1

# /subscriptions/d27e6b04-93a1-4f58-8c7d-31fb9e2a604c/resourceGroups/rg-sandbox/providers/Microsoft.Storage/storageAccounts/acmesandboxdata
# TODO: replace the name, resource_group_name, location, account_tier,
# account_replication_type placeholder(s) below with this resource's real value(s)
# before applying.
import {
  to = azurerm_storage_account.acmesandboxdata
  id = "/subscriptions/d27e6b04-93a1-4f58-8c7d-31fb9e2a604c/resourceGroups/rg-sandbox/providers/Microsoft.Storage/storageAccounts/acmesandboxdata"
}

resource "azurerm_storage_account" "acmesandboxdata" {
  https_traffic_only_enabled = true
  name                       = "todoreplacethisname" # TODO: the account's real name (3-24 lowercase alphanumerics). ForceNew: a wrong value destroys and recreates the account
  resource_group_name        = "TODO-resource-group" # TODO: the account's resource group
  location                   = "TODO-location"       # TODO: e.g. eastus
  account_tier               = "Standard"            # TODO: the account's real tier (Standard or Premium). ForceNew: a wrong value destroys and recreates the account
  account_replication_type   = "LRS"                 # TODO: the account's real replication type. Crossing the LRS/GRS <-> ZRS/GZRS boundary forces replacement
}
