# Generated by azremgen (curated-cloud-remediation-generator) v0.1.0
# Generated: 2026-08-07T13:11:14+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# SCOPE: azure subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7, all regions
#
# This file covers ONE subscription, because that is all an azurerm provider
# configuration covers. It may span locations: an azurerm provider block carries
# no location, so each resource names its own.
#
# CONFIRM the provider in this workspace targets subscription
# 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7. Unlike the AWS provider, azurerm has no
# `allowed_account_ids` equivalent -- `subscription_id` selects a subscription, it
# does not assert which one is acceptable, so a wrong value is not rejected. The
# import ids below are fully-qualified ARM ids that name this subscription, so a
# mismatch fails to find the resource rather than modifying the wrong one; expect
# "resource not found" if the provider is pointed elsewhere.
#
# Standalone use: uncomment this block.
#
# provider "azurerm" {
#   subscription_id = "8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7"
#   features {}
# }
# ---------------------------------------------------------------------------

# TODO: 3 of 3 resource block(s) below need values completed before applying.

# NOTE: 1 of 3 resource block(s) below apply more than one
# policy to a single resource, merged because two `import` blocks cannot name the
# same resource. Each is labelled with every policy it applies.

# ==========================================================================
# Safety tier: SAFEST
# ==========================================================================

# POLICY: SQL Database is not encrypted with transparent data encryption
# Policy ID: f3c5d6e7-d8f0-48fd-97ab-16585ff981f3
#
# Reversible: az sql db tde set --ids <resource-id> --status Disabled
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires name, server_id, which a finding cannot supply. The
# TODO placeholders below satisfy type checking only -- replace each with the resource's
# real value, or the import will reconfigure the resource incorrectly.
# Resources below: 1

# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Sql/servers/acme-sql-prod/databases/billing
# TODO: replace the name, server_id placeholder(s) below with this resource's real
# value(s) before applying.
import {
  to = azurerm_mssql_database.billing
  id = "/subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Sql/servers/acme-sql-prod/databases/billing"
}

resource "azurerm_mssql_database" "billing" {
  transparent_data_encryption_enabled = true
  name                                = "TODO-database-name"                                                                                                      # TODO: the last segment of the import id above. ForceNew: a wrong value destroys and recreates the database
  server_id                           = "/subscriptions/TODO-subscription-id/resourceGroups/TODO-resource-group/providers/Microsoft.Sql/servers/TODO-server-name" # TODO: the import id above, truncated before /databases/. ForceNew
}

# POLICY: Storage Account cross-tenant replication is enabled
# Policy ID: 29307516-af03-445b-a22c-5dfa62598b22
#
# Reversible: az storage account update --ids <resource-id>
# --allow-cross-tenant-replication true
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires name, resource_group_name, location, account_tier,
# account_replication_type, which a finding cannot supply. The TODO placeholders below
# satisfy type checking only -- replace each with the resource's real value, or the
# import will reconfigure the resource incorrectly.
# Resources below: 1

# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-eu-analytics/providers/Microsoft.Storage/storageAccounts/acmeeuexports
# TODO: replace the name, resource_group_name, location, account_tier,
# account_replication_type placeholder(s) below with this resource's real value(s)
# before applying.
import {
  to = azurerm_storage_account.acmeeuexports
  id = "/subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-eu-analytics/providers/Microsoft.Storage/storageAccounts/acmeeuexports"
}

resource "azurerm_storage_account" "acmeeuexports" {
  cross_tenant_replication_enabled = false
  name                             = "todoreplacethisname" # TODO: the account's real name (3-24 lowercase alphanumerics). ForceNew: a wrong value destroys and recreates the account
  resource_group_name              = "TODO-resource-group" # TODO: the account's resource group
  location                         = "TODO-location"       # TODO: e.g. eastus
  account_tier                     = "Standard"            # TODO: the account's real tier (Standard or Premium). ForceNew: a wrong value destroys and recreates the account
  account_replication_type         = "LRS"                 # TODO: the account's real replication type. Crossing the LRS/GRS <-> ZRS/GZRS boundary forces replacement
}

# 2 POLICIES on this one resource, applied together:
# - Storage Account in transit is not enabled
# - Storage Account insecure communication
# Policy IDs: bed905d4-758c-4698-9ed8-4cdd4271eb4e, 0662810d-c71d-46a3-a937-e1c2b24792e4
#
# Merged into a single import + resource pair on purpose. Two import blocks naming the
# same resource are valid configuration -- `validate` passes -- and fail only at
# plan/apply. Applying this block applies every policy above; they cannot be separated
# here.
#
# Every note below applies to this one block. Each is tagged with the policy it comes
# from, because reversing this block means reversing each policy's change, not just one
# of them.
# [Storage Account in transit is not enabled] Reversible: az storage account update
# --ids <resource-id> --https-only false
# [Storage Account insecure communication] Reversible: az storage account update --ids
# <resource-id> --min-tls-version TLS1_0
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires name, resource_group_name, location, account_tier,
# account_replication_type, which a finding cannot supply. The TODO placeholders below
# satisfy type checking only -- replace each with the resource's real value, or the
# import will reconfigure the resource incorrectly.
#
# Resource:
# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01
# TODO: replace the name, resource_group_name, location, account_tier,
# account_replication_type placeholder(s) below with this resource's real value(s)
# before applying.
import {
  to = azurerm_storage_account.acmeprodlogs01
  id = "/subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01"
}

resource "azurerm_storage_account" "acmeprodlogs01" {
  https_traffic_only_enabled = true
  name                       = "todoreplacethisname" # TODO: the account's real name (3-24 lowercase alphanumerics). ForceNew: a wrong value destroys and recreates the account
  resource_group_name        = "TODO-resource-group" # TODO: the account's resource group
  location                   = "TODO-location"       # TODO: e.g. eastus
  account_tier               = "Standard"            # TODO: the account's real tier (Standard or Premium). ForceNew: a wrong value destroys and recreates the account
  account_replication_type   = "LRS"                 # TODO: the account's real replication type. Crossing the LRS/GRS <-> ZRS/GZRS boundary forces replacement
  min_tls_version            = "TLS1_2"
}
