#!/usr/bin/env bash
#
# Generated by azremgen (curated-cloud-remediation-generator) v0.1.0
# Generated: 2026-08-07T13:11:14+00:00
#
# THIS SCRIPT MODIFIES AZURE RESOURCES. Review it before running it. Remediations
# come from a curated, individually verified recipe set; coverage is intentionally
# partial. See README.md in this directory for the review checklist.
#
# Requires: Azure CLI (az) 2.50 or later, and credentials that can reach the subscription below.
#
# shellcheck disable=SC2086
set -euo pipefail

if ! command -v az >/dev/null 2>&1; then
  echo "error: the 'az' CLI is not on PATH." >&2
  exit 1
fi
#
# Scope: azure subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7, all regions
# Remediations in this file: 4
#
# Every command below names this subscription explicitly. The guard below confirms you
# can reach it before making any change.

# Subscription guard. Every command below names --subscription explicitly, so this
# does NOT require the subscription to be your active one -- it checks you can reach
# it at all, and fails before any change if you cannot.
#
# Note for readers familiar with the AWS script: that one refuses to run when the
# active account differs. This one does not, because an Azure login legitimately
# spans subscriptions and the target here is stated per command rather than
# inherited from the shell.
expected_subscription="8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7"
if ! az account show >/dev/null 2>&1; then
  echo "error: not logged in to Azure. Run 'az login' and re-run." >&2
  exit 1
fi
reachable="$(az account list --query "length([?id=='$expected_subscription'])" --output tsv)"
if [[ "$reachable" != "1" ]]; then
  echo "error: subscription $expected_subscription is not available to these" >&2
  echo "       credentials. These remediations are for that subscription only." >&2
  echo "       Run 'az login' with an identity that can reach it, or" >&2
  echo "       'az account set --subscription $expected_subscription' if you" >&2
  echo "       expected it to be present." >&2
  exit 1
fi
active_subscription="$(az account show --query id --output tsv)"
if [[ "$active_subscription" != "$expected_subscription" ]]; then
  echo "note: your active subscription is $active_subscription, but every command"
  echo "      below targets $expected_subscription explicitly. Proceeding."
fi
echo "Subscription $expected_subscription confirmed. Scope: azure subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7, all regions"

# ==========================================================================
# SAFEST -- reversible, no data-path impact, no usage-scaled cost
# ==========================================================================

# POLICY: SQL Database is not encrypted with transparent data encryption
# Policy ID: f3c5d6e7-d8f0-48fd-97ab-16585ff981f3
# Resources: 1
#
# Reversible: az sql db tde set --ids <resource-id> --status Disabled
# Summary, caveats and docs: see README.md

# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Sql/servers/acme-sql-prod/databases/billing
# (eastus)
echo ">> SQL Database is not encrypted with transparent data encryption :: /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Sql/servers/acme-sql-prod/databases/billing"
az sql db tde set --ids /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Sql/servers/acme-sql-prod/databases/billing --status Enabled --subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7

# POLICY: Storage Account cross-tenant replication is enabled
# Policy ID: 29307516-af03-445b-a22c-5dfa62598b22
# Resources: 1
#
# Reversible: az storage account update --ids <resource-id>
# --allow-cross-tenant-replication true
# Summary, caveats and docs: see README.md

# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-eu-analytics/providers/Microsoft.Storage/storageAccounts/acmeeuexports
# (westeurope)
echo ">> Storage Account cross-tenant replication is enabled :: /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-eu-analytics/providers/Microsoft.Storage/storageAccounts/acmeeuexports"
az storage account update --ids /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-eu-analytics/providers/Microsoft.Storage/storageAccounts/acmeeuexports --allow-cross-tenant-replication false --subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7

# POLICY: Storage Account in transit is not enabled
# Policy ID: bed905d4-758c-4698-9ed8-4cdd4271eb4e
# Resources: 1
#
# Reversible: az storage account update --ids <resource-id> --https-only false
# Summary, caveats and docs: see README.md

# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01
# (eastus)
echo ">> Storage Account in transit is not enabled :: /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01"
az storage account update --ids /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01 --https-only true --subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7

# POLICY: Storage Account insecure communication
# Policy ID: 0662810d-c71d-46a3-a937-e1c2b24792e4
# Resources: 1
#
# Reversible: az storage account update --ids <resource-id> --min-tls-version TLS1_0
# Summary, caveats and docs: see README.md

# /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01
# (eastus)
echo ">> Storage Account insecure communication :: /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01"
az storage account update --ids /subscriptions/8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7/resourceGroups/rg-platform-prod/providers/Microsoft.Storage/storageAccounts/acmeprodlogs01 --min-tls-version TLS1_2 --subscription 8f4a1c62-5d90-4e7b-9a3f-2c6b8d10e5a7

echo
echo "Done. 4 remediation command(s) completed."
echo "Re-scan in Tenable Cloud Security to confirm the findings clear."
