#!/usr/bin/env bash
#
# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.1
# Generated: 2026-08-07T19:36:15+00:00
#
# THIS SCRIPT MODIFIES AWS RESOURCES. Review it before running it. Remediations
# come from a curated, individually verified recipe set; coverage is intentionally
# partial. See README.md in this directory for the review checklist.
#
# Requires: AWS CLI v2 (v1 is not tested) and credentials for the account below.
#
# shellcheck disable=SC2086
set -euo pipefail

if ! command -v aws >/dev/null 2>&1; then
  echo "error: the 'aws' CLI is not on PATH." >&2
  exit 1
fi
#
# Scope: aws account 222222222222, all regions
# Remediations in this file: 2
#
# Run this file with credentials for the account named above. The guard below verifies
# that before making any change.

# Account guard. This script uses whatever credentials your shell provides and
# cannot switch between them, so it targets one account and refuses to run against
# any other rather than changing the wrong resources.
expected_account="222222222222"
actual_account="$(aws sts get-caller-identity --query Account --output text)"
if [[ "$actual_account" != "$expected_account" ]]; then
  echo "error: these remediations are for account $expected_account," >&2
  echo "       but your credentials are for account $actual_account." >&2
  echo "       Select the right profile (AWS_PROFILE / --profile) and re-run." >&2
  exit 1
fi
echo "Account $expected_account confirmed. Scope: aws account 222222222222, all regions"

# ==========================================================================
# CAUTION -- sound, but carries a commitment. Read each note.
# ==========================================================================

# POLICY: RDS Instance delete protection is not enabled
# Policy ID: 4d6662cd-9f34-41eb-b152-f24c692d4fbf
# Resources: 1
#
# Reversible: aws rds modify-db-instance --db-instance-identifier <id>
# --no-deletion-protection --apply-immediately
# Blocks 'terraform destroy' / 'tofu destroy'. Disable deliberately before a planned
# teardown; avoid on ephemeral or CI environments.
# Summary, caveats and docs: see README.md

# billing-primary  (us-east-1)
echo ">> RDS Instance delete protection is not enabled :: billing-primary"
aws rds modify-db-instance --db-instance-identifier billing-primary --deletion-protection --apply-immediately --region us-east-1

# POLICY: S3 Bucket versioning is not enabled
# Policy ID: 284b1210-a31e-48ce-97af-f4d825ef132d
# Resources: 1
#
# NOT REVERSIBLE: this change cannot be fully undone.
# COST SCALES WITH USAGE: charges grow with data volume and have no ceiling. Estimate
# volume before applying fleet-wide.
# Summary, caveats and docs: see README.md

# acme-invoice-archive  (us-east-1)
echo ">> S3 Bucket versioning is not enabled :: acme-invoice-archive"
aws s3api put-bucket-versioning --bucket acme-invoice-archive --versioning-configuration Status=Enabled --region us-east-1

echo
echo "Done. 2 remediation command(s) completed."
echo "Re-scan in Tenable Cloud Security to confirm the findings clear."
