# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.0
# Generated: 2026-08-07T16:57:07+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# SCOPE: aws account 111111111111, us-west-2
#
# This file covers ONE account and ONE region, because that is all an AWS provider
# configuration covers. A provider pointed at another account will not fail -- it
# will import a same-named resource from the account it can see. Confirm this
# workspace's provider targets account 111111111111 in us-west-2.
#
# Standalone use: uncomment this block. `allowed_account_ids` makes a credential
# mismatch fail the plan instead of importing the wrong resource.
#
# provider "aws" {
#   region              = "us-west-2"
#   allowed_account_ids = ["111111111111"]
# }
# ---------------------------------------------------------------------------

# ==========================================================================
# Safety tier: CAUTION
# ==========================================================================

# POLICY: KMS Key automatic key rotation is not enabled
# Policy ID: 995e8d78-940a-45bf-bac1-61a1fdb00d7a
#
# NOT REVERSIBLE: this change cannot be fully undone.
# Small incremental AWS cost.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# 3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60
import {
  to = aws_kms_key.r_3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60
  id = "3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60"
}

resource "aws_kms_key" "r_3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60" {
  enable_key_rotation = true
}
