#!/usr/bin/env bash
#
# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.0
# Generated: 2026-08-07T16:57:07+00:00
#
# THIS SCRIPT MODIFIES AWS RESOURCES. Review it before running it. Remediations
# come from a curated, individually verified recipe set; coverage is intentionally
# partial. See README.md in this directory for the review checklist.
#
# Requires: AWS CLI v2 (v1 is not tested) and credentials for the account below.
#
# shellcheck disable=SC2086
set -euo pipefail

if ! command -v aws >/dev/null 2>&1; then
  echo "error: the 'aws' CLI is not on PATH." >&2
  exit 1
fi
#
# Scope: aws account 111111111111, all regions
# Remediations in this file: 4
#
# Run this file with credentials for the account named above. The guard below verifies
# that before making any change.

# Account guard. This script uses whatever credentials your shell provides and
# cannot switch between them, so it targets one account and refuses to run against
# any other rather than changing the wrong resources.
expected_account="111111111111"
actual_account="$(aws sts get-caller-identity --query Account --output text)"
if [[ "$actual_account" != "$expected_account" ]]; then
  echo "error: these remediations are for account $expected_account," >&2
  echo "       but your credentials are for account $actual_account." >&2
  echo "       Select the right profile (AWS_PROFILE / --profile) and re-run." >&2
  exit 1
fi
echo "Account $expected_account confirmed. Scope: aws account 111111111111, all regions"

# ==========================================================================
# SAFEST -- reversible, no data-path impact, no usage-scaled cost
# ==========================================================================

# POLICY: CloudTrail S3 Bucket log file validation is not enabled
# Policy ID: 8d1140ba-c917-44d7-b2ea-084f9dffe707
# Resources: 1
#
# Reversible: aws cloudtrail update-trail --name <name> --no-enable-log-file-validation
# Summary, caveats and docs: see README.md

# org-audit-trail  (us-east-1)
echo ">> CloudTrail S3 Bucket log file validation is not enabled :: org-audit-trail"
aws cloudtrail update-trail --name org-audit-trail --enable-log-file-validation --region us-east-1

# ==========================================================================
# CAUTION -- sound, but carries a commitment. Read each note.
# ==========================================================================

# POLICY: DynamoDB Table delete protection is not enabled
# Policy ID: 468d7976-445f-44c2-b9fb-45fb1005f373
# Resources: 1
#
# Reversible: aws dynamodb update-table --table-name <name>
# --no-deletion-protection-enabled
# Blocks 'terraform destroy' / 'tofu destroy'. Disable deliberately before a planned
# teardown; avoid on ephemeral or CI environments.
# Summary, caveats and docs: see README.md

# checkout-sessions  (us-east-1)
echo ">> DynamoDB Table delete protection is not enabled :: checkout-sessions"
aws dynamodb update-table --table-name checkout-sessions --deletion-protection-enabled --region us-east-1

# POLICY: KMS Key automatic key rotation is not enabled
# Policy ID: 995e8d78-940a-45bf-bac1-61a1fdb00d7a
# Resources: 1
#
# NOT REVERSIBLE: this change cannot be fully undone.
# Small incremental AWS cost.
# Summary, caveats and docs: see README.md

# 3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60  (us-west-2)
echo ">> KMS Key automatic key rotation is not enabled :: 3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60"
aws kms enable-key-rotation --key-id 3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60 --region us-west-2

# POLICY: S3 Bucket versioning is not enabled
# Policy ID: 284b1210-a31e-48ce-97af-f4d825ef132d
# Resources: 1
#
# NOT REVERSIBLE: this change cannot be fully undone.
# COST SCALES WITH USAGE: charges grow with data volume and have no ceiling. Estimate
# volume before applying fleet-wide.
# Summary, caveats and docs: see README.md

# acme-web-assets-use1  (us-east-1)
echo ">> S3 Bucket versioning is not enabled :: acme-web-assets-use1"
aws s3api put-bucket-versioning --bucket acme-web-assets-use1 --versioning-configuration Status=Enabled --region us-east-1

echo
echo "Done. 4 remediation command(s) completed."
echo "Re-scan in Tenable Cloud Security to confirm the findings clear."
