# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.1
# Generated: 2026-08-09T19:57:48+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# PROVIDER VERSION
#
# Verified against hashicorp/aws 6.x. The upper bound is deliberate: a
# provider major relocates arguments between resources -- aws v5 to v6 moved the
# `aws_s3_bucket` sub-arguments -- so an unbounded constraint would resolve to a
# major these blocks were never checked against, and fail in your workspace rather
# than in this project's CI.
#
# The range below is not a verified range, and its two halves are different claims.
# The ceiling is what was tested. The floor is the earliest release in which these
# arguments existed at all, which is older -- so a version between the two satisfies
# the constraint without having been checked. Pin to 6.x for the
# verified one only.
#
# Commented for the same reason as the provider block below: a module may have only
# one `required_providers` configuration, and dropping a second one into an existing
# workspace is an error at `init`. Uncomment for standalone use.
#
# terraform {
#   required_providers {
#     aws = {
#       source  = "hashicorp/aws"
#       version = ">= 5.0, < 7.0"
#     }
#   }
# }
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# SCOPE: aws account 111111111111, us-east-1
#
# This file covers ONE account and ONE region, because that is all an AWS provider
# configuration covers. A provider pointed at another account will not fail -- it
# will import a same-named resource from the account it can see. Confirm this
# workspace's provider targets account 111111111111 in us-east-1.
#
# Standalone use: uncomment this block. `allowed_account_ids` makes a credential
# mismatch fail the plan instead of importing the wrong resource.
#
# provider "aws" {
#   region              = "us-east-1"
#   allowed_account_ids = ["111111111111"]
# }
# ---------------------------------------------------------------------------

# TODO: 1 of 4 resource block(s) below need values completed before applying.

# ==========================================================================
# Safety tier: SAFEST
# ==========================================================================

# POLICY: CloudTrail S3 Bucket log file validation is not enabled
# Policy ID: 8d1140ba-c917-44d7-b2ea-084f9dffe707
#
# Reversible: aws cloudtrail update-trail --name <name> --no-enable-log-file-validation
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires s3_bucket_name, which a finding cannot supply. The
# TODO placeholders below satisfy type checking only -- replace each with the resource's
# real value, or the import will reconfigure the resource incorrectly.
# Resources below: 1

# org-audit-trail
# TODO: replace the s3_bucket_name placeholder(s) below with this resource's real
# value(s) before applying.
import {
  to = aws_cloudtrail.org-audit-trail
  id = "arn:aws:cloudtrail:us-east-1:111111111111:trail/org-audit-trail"
}

resource "aws_cloudtrail" "org-audit-trail" {
  name                       = "org-audit-trail"
  enable_log_file_validation = true
  s3_bucket_name             = "TODO" # TODO: set to the trail's existing log bucket
}

# POLICY: S3 Bucket block public access is not enabled
# Policy ID: 80b8e9b6-c285-4939-b115-452dfd65bbcc
#
# !! CONFIRM THIS BUCKET IS NOT MEANT TO BE PUBLIC BEFORE APPLYING. If it serves a
#    static website, a published dataset or any anonymously read content, that access
#    stops immediately. This tool cannot tell intentional public access from accidental:
#    a Tenable Cloud Security exception does not travel in a findings export, so scope
#    your export rather than relying on the tool.
#
# Reversible: aws s3api delete-public-access-block --bucket <bucket> --region <region>
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# acme-web-assets-use1
import {
  to = aws_s3_bucket_public_access_block.acme-web-assets-use1
  id = "acme-web-assets-use1"
}

resource "aws_s3_bucket_public_access_block" "acme-web-assets-use1" {
  bucket                  = "acme-web-assets-use1"
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# ==========================================================================
# Safety tier: CAUTION
# ==========================================================================

# POLICY: DynamoDB Table delete protection is not enabled
# Policy ID: 468d7976-445f-44c2-b9fb-45fb1005f373
#
# Reversible: aws dynamodb update-table --table-name <name>
# --no-deletion-protection-enabled
# Blocks 'terraform destroy' / 'tofu destroy'. Disable deliberately before a planned
# teardown; avoid on ephemeral or CI environments.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# checkout-sessions
import {
  to = aws_dynamodb_table.checkout-sessions
  id = "checkout-sessions"
}

resource "aws_dynamodb_table" "checkout-sessions" {
  name                        = "checkout-sessions"
  deletion_protection_enabled = true
}

# POLICY: S3 Bucket versioning is not enabled
# Policy ID: 284b1210-a31e-48ce-97af-f4d825ef132d
#
# NOT REVERSIBLE: this change cannot be fully undone.
# COST SCALES WITH USAGE: charges grow with data volume and have no ceiling. Estimate
# volume before applying fleet-wide.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# acme-web-assets-use1
import {
  to = aws_s3_bucket_versioning.acme-web-assets-use1
  id = "acme-web-assets-use1"
}

resource "aws_s3_bucket_versioning" "acme-web-assets-use1" {
  bucket = "acme-web-assets-use1"

  versioning_configuration {
    status = "Enabled"
  }
}
