# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.1
# Generated: 2026-08-10T00:49:53+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# PROVIDER VERSION
#
# Verified against hashicorp/aws 6.x. The upper bound is deliberate: a
# provider major relocates arguments between resources, so an unbounded constraint
# would resolve to a major these blocks were never checked against, and fail in your
# workspace rather than in this project's CI.
#
# For example: aws v3 to v4 moved 13 inline `aws_s3_bucket` parameters, including
# `versioning`, out to standalone resources such as `aws_s3_bucket_versioning`.
#
# The range below is not a verified range, and its two halves are different claims.
# The ceiling is what was tested. The floor is the earliest release in which these
# arguments existed at all, which is older -- so a version between the two satisfies
# the constraint without having been checked. Pin to 6.x for the
# verified one only.
#
# Commented for the same reason as the provider block below: a module may have only
# one `required_providers` configuration, and dropping a second one into an existing
# workspace is an error at `init`. Uncomment for standalone use.
#
# terraform {
#   required_providers {
#     aws = {
#       source  = "hashicorp/aws"
#       version = ">= 5.0, < 7.0"
#     }
#   }
# }
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# SCOPE: aws account 222222222222, us-east-1
#
# This file covers ONE account and ONE region, because that is all an AWS provider
# configuration covers. A provider pointed at another account will not fail -- it
# will import a same-named resource from the account it can see. Confirm this
# workspace's provider targets account 222222222222 in us-east-1.
#
# Standalone use: uncomment this block. `allowed_account_ids` makes a credential
# mismatch fail the plan instead of importing the wrong resource.
#
# provider "aws" {
#   region              = "us-east-1"
#   allowed_account_ids = ["222222222222"]
# }
# ---------------------------------------------------------------------------

# TODO: 2 of 3 resource block(s) below need values completed before applying.

# NOTE: 1 of 3 resource block(s) below apply more than one
# policy to a single resource, merged because two `import` blocks cannot name the
# same resource. Each is labelled with every policy it applies.

# ==========================================================================
# Safety tier: CAUTION
# ==========================================================================

# POLICY: RDS Cluster delete protection is not enabled
# Policy ID: 03242d06-4bec-44b5-89fa-0ebb4d926242
#
# Reversible: aws rds modify-db-cluster --db-cluster-identifier <id>
# --no-deletion-protection
# Blocks 'terraform destroy' / 'tofu destroy'. Disable deliberately before a planned
# teardown; avoid on ephemeral or CI environments.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires engine, which a finding cannot supply. The TODO
# placeholders below satisfy type checking only -- replace each with the resource's real
# value, or the import will reconfigure the resource incorrectly.
# Resources below: 1

# acme-aurora-orders
# TODO: replace the engine placeholder(s) below with this resource's real value(s)
# before applying.
import {
  to = aws_rds_cluster.acme-aurora-orders
  id = "acme-aurora-orders"
}

resource "aws_rds_cluster" "acme-aurora-orders" {
  cluster_identifier  = "acme-aurora-orders"
  deletion_protection = true
  engine              = "aurora-postgresql" # TODO: set to the cluster's real engine. A wrong value replaces the cluster and destroys its data
}

# POLICY: S3 Bucket versioning is not enabled
# Policy ID: 284b1210-a31e-48ce-97af-f4d825ef132d
#
# NOT REVERSIBLE: this change cannot be fully undone.
# COST SCALES WITH USAGE: charges grow with data volume and have no ceiling. Estimate
# volume before applying fleet-wide.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# acme-invoice-archive
import {
  to = aws_s3_bucket_versioning.acme-invoice-archive
  id = "acme-invoice-archive"
}

resource "aws_s3_bucket_versioning" "acme-invoice-archive" {
  bucket = "acme-invoice-archive"

  versioning_configuration {
    status = "Enabled"
  }
}

# 2 POLICIES on this one resource, applied together:
# - RDS Instance automatic minor version upgrade is not enabled
# - RDS Instance delete protection is not enabled
# Policy IDs: ca0fddf1-a200-458c-a3cb-b78ad774c3d8, 4d6662cd-9f34-41eb-b152-f24c692d4fbf
#
# Merged into a single import + resource pair on purpose. Two import blocks naming the
# same resource are valid configuration -- `validate` passes -- and fail only at
# plan/apply. Applying this block applies every policy above; they cannot be separated
# here.
#
# Every note below applies to this one block. Each is tagged with the policy it comes
# from, because reversing this block means reversing each policy's change, not just one
# of them.
# [RDS Instance automatic minor version upgrade is not enabled] Reversible: aws rds
# modify-db-instance --db-instance-identifier <id> --no-auto-minor-version-upgrade
# --apply-immediately
# [RDS Instance delete protection is not enabled] Reversible: aws rds modify-db-instance
# --db-instance-identifier <id> --no-deletion-protection --apply-immediately
# [RDS Instance delete protection is not enabled] Blocks 'terraform destroy' / 'tofu
# destroy'. Disable deliberately before a planned teardown; avoid on ephemeral or CI
# environments.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires instance_class, which a finding cannot supply. The
# TODO placeholders below satisfy type checking only -- replace each with the resource's
# real value, or the import will reconfigure the resource incorrectly.
#
# Resource: billing-primary
# TODO: replace the instance_class placeholder(s) below with this resource's real
# value(s) before applying.
import {
  to = aws_db_instance.billing-primary
  id = "billing-primary"
}

resource "aws_db_instance" "billing-primary" {
  identifier                 = "billing-primary"
  auto_minor_version_upgrade = true
  instance_class             = "db.t3.micro" # TODO: set to the instance's real class
  deletion_protection        = true
}
