# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.0
# Generated: 2026-08-07T16:57:07+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# SCOPE: aws account 222222222222, us-east-1
#
# This file covers ONE account and ONE region, because that is all an AWS provider
# configuration covers. A provider pointed at another account will not fail -- it
# will import a same-named resource from the account it can see. Confirm this
# workspace's provider targets account 222222222222 in us-east-1.
#
# Standalone use: uncomment this block. `allowed_account_ids` makes a credential
# mismatch fail the plan instead of importing the wrong resource.
#
# provider "aws" {
#   region              = "us-east-1"
#   allowed_account_ids = ["222222222222"]
# }
# ---------------------------------------------------------------------------

# TODO: 1 of 2 resource block(s) below need values completed before applying.

# ==========================================================================
# Safety tier: CAUTION
# ==========================================================================

# POLICY: RDS Instance delete protection is not enabled
# Policy ID: 4d6662cd-9f34-41eb-b152-f24c692d4fbf
#
# Reversible: aws rds modify-db-instance --db-instance-identifier <id>
# --no-deletion-protection --apply-immediately
# Blocks 'terraform destroy' / 'tofu destroy'. Disable deliberately before a planned
# teardown; avoid on ephemeral or CI environments.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
#
# INCOMPLETE: the provider requires instance_class, which a finding cannot supply. The
# TODO placeholders below satisfy type checking only -- replace each with the resource's
# real value, or the import will reconfigure the resource incorrectly.
# Resources below: 1

# billing-primary
# TODO: replace the instance_class placeholder(s) below with this resource's real
# value(s) before applying.
import {
  to = aws_db_instance.billing-primary
  id = "billing-primary"
}

resource "aws_db_instance" "billing-primary" {
  identifier          = "billing-primary"
  deletion_protection = true
  instance_class      = "db.t3.micro" # TODO: set to the instance's real class
}

# POLICY: S3 Bucket versioning is not enabled
# Policy ID: 284b1210-a31e-48ce-97af-f4d825ef132d
#
# NOT REVERSIBLE: this change cannot be fully undone.
# COST SCALES WITH USAGE: charges grow with data volume and have no ceiling. Estimate
# volume before applying fleet-wide.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# acme-invoice-archive
import {
  to = aws_s3_bucket_versioning.acme-invoice-archive
  id = "acme-invoice-archive"
}

resource "aws_s3_bucket_versioning" "acme-invoice-archive" {
  bucket = "acme-invoice-archive"

  versioning_configuration {
    status = "Enabled"
  }
}
