# Generated by awsremgen (curated-cloud-remediation-generator) v0.2.1
# Generated: 2026-08-09T17:50:30+00:00
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.

# ---------------------------------------------------------------------------
# PROVIDER VERSION
#
# Verified against hashicorp/aws 6.x. The upper bound is deliberate: a
# provider major relocates arguments between resources -- aws v5 to v6 moved the
# `aws_s3_bucket` sub-arguments -- so an unbounded constraint would resolve to a
# major these blocks were never checked against, and fail in your workspace rather
# than in this project's CI.
#
# The range below is not a verified range, and its two halves are different claims.
# The ceiling is what was tested. The floor is the earliest release in which these
# arguments existed at all, which is older -- so a version between the two satisfies
# the constraint without having been checked. Pin to 6.x for the
# verified one only.
#
# Commented for the same reason as the provider block below: a module may have only
# one `required_providers` configuration, and dropping a second one into an existing
# workspace is an error at `init`. Uncomment for standalone use.
#
# terraform {
#   required_providers {
#     aws = {
#       source  = "hashicorp/aws"
#       version = ">= 5.0, < 7.0"
#     }
#   }
# }
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# SCOPE: aws account 111111111111, us-west-2
#
# This file covers ONE account and ONE region, because that is all an AWS provider
# configuration covers. A provider pointed at another account will not fail -- it
# will import a same-named resource from the account it can see. Confirm this
# workspace's provider targets account 111111111111 in us-west-2.
#
# Standalone use: uncomment this block. `allowed_account_ids` makes a credential
# mismatch fail the plan instead of importing the wrong resource.
#
# provider "aws" {
#   region              = "us-west-2"
#   allowed_account_ids = ["111111111111"]
# }
# ---------------------------------------------------------------------------

# ==========================================================================
# Safety tier: CAUTION
# ==========================================================================

# POLICY: KMS Key automatic key rotation is not enabled
# Policy ID: 995e8d78-940a-45bf-bac1-61a1fdb00d7a
#
# NOT REVERSIBLE: this change cannot be fully undone.
# Small incremental AWS cost.
# Summary, caveats and docs: see README.md
# Requires provider >= 5.0
# Resources below: 1

# 3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60
import {
  to = aws_kms_key.r_3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60
  id = "3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60"
}

resource "aws_kms_key" "r_3f9c0a11-6d2e-4b8a-9c77-2b1e5d4a8f60" {
  enable_key_rotation = true
}
