"""Generate import-aware OpenTofu / Terraform configuration.

The single most important thing this module gets right:

    Terraform and OpenTofu only manage resources that exist in state.

A remediation targets a resource that already exists in the cloud. If that
resource was not created by the same IaC workspace, emitting a bare ``resource``
block does not fix it -- the plan tries to *create a second one*, and either fails
on a name conflict or provisions a duplicate. So every resource block emitted here
is paired with an ``import`` block. Import is mandatory, not an optional nicety.

Second consideration: an ``import`` block must reference a ``resource`` block, and
the provider validates that block's *required* arguments. For several resource
types those required arguments cannot be derived from a finding -- an RDS finding
carries no ``engine`` or ``instance_class``. Rather than emit configuration that
fails ``plan``, those attributes are rendered as explicit ``# TODO`` markers and
the file is labelled as requiring completion. Output that admits it is incomplete
is more useful than output that looks finished and is not.

Third consideration, and the reason output is split: **a Terraform provider
configuration covers one credential scope.** For ``hashicorp/aws`` it also covers
exactly one region, so a file whose import blocks span regions cannot resolve them
all. The dangerous case is not a failure but a success against the wrong resource:
an import for ``GameScores`` in account B, evaluated by a provider authenticated to
account A, will adopt and reconfigure *A's* table of the same name. Whether region
is part of that scope is a property of the specific provider, so it is declared per
cloud rather than assumed here -- see
:attr:`~remgen.core.provider.Provider.hcl_provider_is_region_scoped` and
:mod:`remgen.core.layout`.

This module is cloud-neutral. HCL syntax, ``import``-block semantics, label
uniqueness rules, and ``tofu fmt`` alignment are properties of the configuration
language, not of any cloud, so they are implemented once. The two things that are
not neutral are supplied by the provider: the wording of the scope statement (which
names the credential scope and the actual ``provider`` block) and the documentation
label in recipe notes.

No active ``provider`` block is emitted, because this file is meant to be placed in
a workspace that already declares one, and a second declaration is a "Duplicate
provider configuration" error. The required scope is stated in the header, and a
ready-to-uncomment block is included for standalone use.

Compatibility: the generated HCL is standard configuration language and works
with OpenTofu and with Terraform. OpenTofu (MPL-2.0) is the primary target and is
what the test suite validates against; Terraform is never required by, invoked
by, or a dependency of this project. See NOTICE.md.
"""

from __future__ import annotations

from collections.abc import Callable

from remgen import PROJECT_NAME
from remgen.core.generators.common import comment_block, recipe_notes, render_template
from remgen.core.layout import OutputUnit
from remgen.core.model import Finding, Recipe, SafetyTier, to_hcl_label

#: Kept deliberately short. The full instructions live in README.md alongside the
#: artifacts, written once per run: a run over a large estate emits one file per
#: scope, and repeating a 1 KB how-to preamble in each of them was adding a third
#: of the total output for text nobody reads twice. What stays here is the
#: provenance and the two warnings that must not be missed even by someone who
#: opens a single file out of context.
_HEADER = """\
# Generated by {command} ({project}) v{version}
# Generated: {generated_at}
# Compatible with OpenTofu and Terraform. Validated against OpenTofu.
#
# Read README.md in this directory before applying. In short: each `import` block
# adopts an existing cloud resource and its paired `resource` block corrects the
# setting. Plan must report "N to import, 0 to add" -- any "to add" means an import
# id is wrong. Do not import a resource another workspace already manages.
#
# Requires OpenTofu >= 1.6 or Terraform >= 1.5, and the provider version noted
# per policy below.
"""

_NO_RESULTS = """
# No remediable findings were supplied, so no configuration was generated.
"""


def _disambiguated_label(finding: Finding) -> str:
    """Return a label that also encodes the account and region.

    Used when a bare resource-id label would collide. AWS resource names are only
    unique within an account and region, so ``GameScores`` in two accounts is two
    different tables -- but folds to one HCL label.
    """
    base = to_hcl_label(finding.resource_id)
    suffix = to_hcl_label(f"{finding.region}_{finding.account_id}")
    return f"{base}_{suffix}"


def assign_labels(pairs: list[tuple[Recipe, Finding]]) -> dict[int, str]:
    """Map each pair's index to a unique HCL resource label.

    HCL requires labels to be unique per resource type within a module, and
    :func:`to_hcl_label` derives a label from the resource id alone. Two resources
    with the same name in different accounts or regions -- a routine dev/prod
    pattern -- therefore produce the same label, and the emitted file fails
    ``validate`` with "Duplicate resource configuration". Because the CLI reports
    success in that case, the failure only surfaces when someone tries to apply.

    Labels are assigned over the whole set so the result is deterministic and
    independent of ordering: a resource id that appears once keeps its short
    label; one that appears more than once *within the same resource type* gets
    the account and region appended. If that still collides, a short digest of the
    identifying tuple is appended, so a label is never silently reused.
    """
    # Count bare labels per resource type -- uniqueness is per type, not global.
    counts: dict[tuple[str, str], int] = {}
    for recipe, finding in pairs:
        if recipe.hcl is None:
            continue
        key = (recipe.hcl.resource_type, to_hcl_label(finding.resource_id))
        counts[key] = counts.get(key, 0) + 1

    labels: dict[int, str] = {}
    used: set[tuple[str, str]] = set()
    for index, (recipe, finding) in enumerate(pairs):
        if recipe.hcl is None:
            continue
        rtype = recipe.hcl.resource_type
        bare = to_hcl_label(finding.resource_id)
        label = bare if counts[(rtype, bare)] == 1 else _disambiguated_label(finding)
        if (rtype, label) in used:
            # Reached only when two findings are identical in resource id, region
            # and account for the same resource type -- the caller dedupes true
            # duplicates first, so this is a backstop. A digest of the identifying
            # tuple would be identical for identical findings and so would collide
            # again; an ordinal is unconditionally unique.
            stem, n = label, 2
            while (rtype, f"{stem}_{n}") in used:
                n += 1
            label = f"{stem}_{n}"
        used.add((rtype, label))
        labels[index] = label
    return labels


def _align(rows: list[tuple[str, str, str]], indent: str) -> list[str]:
    """Render ``(name, value, comment)`` rows the way ``tofu fmt`` would.

    ``tofu fmt`` aligns consecutive assignments on ``=`` *and* aligns their
    trailing comments. Matching that here means generated files are already
    canonical, so ``tofu fmt -check`` passes and a user's own ``fmt`` run
    produces no diff noise.
    """
    if not rows:
        return []
    name_w = max(len(n) for n, _, _ in rows)
    # Comment alignment is computed over only the rows that have a comment.
    val_w = max((len(v) for _, v, c in rows if c), default=0)
    lines = []
    for name, value, comment in rows:
        head = f"{indent}{name.ljust(name_w)} = "
        lines.append(f"{head}{value.ljust(val_w)} # {comment}".rstrip() if comment
                     else f"{head}{value}")
    return lines


def _attr_lines(recipe: Recipe, finding: Finding, indent: str = "  ") -> list[str]:
    """Render the body of a resource block: attributes, stubs, nested blocks.

    Raises:
        ValueError: If the recipe has no HCL target. Callers filter for this, but
            the check is a real statement rather than an ``assert`` because
            ``assert`` is removed under ``python -O`` -- precisely the build where
            an unguarded ``None`` would produce a malformed resource block.
    """
    if recipe.hcl is None:
        raise ValueError(f"{recipe.policy_id}: no HCL target for this recipe")

    rows: list[tuple[str, str, str]] = [
        (name, render_template(raw, finding), "")
        for name, raw in recipe.hcl.attributes
    ]
    # Placeholders are type-valid stubs rather than `null`, because the provider
    # rejects `null` for a required argument just as it rejects an absent one.
    # A stub keeps `tofu validate` usable as a pre-completion check.
    rows.extend(
        (name, render_template(placeholder, finding), comment)
        for name, placeholder, comment in recipe.hcl.unresolvable_required_attributes
    )
    lines = _align(rows, indent)

    for block_name, block_attrs in recipe.hcl.blocks:
        inner = [
            (n, render_template(v, finding), c) for n, v, c in block_attrs
        ]
        lines.append("")
        lines.append(f"{indent}{block_name} {{")
        lines.extend(_align(inner, indent + "  "))
        lines.append(f"{indent}}}")
    return lines


def hcl_recipe_notes(recipe: Recipe, *, docs_label: str = "Provider docs") -> list[str]:
    """Return the comment lines describing a recipe, independent of any finding.

    The shared recipe notes plus the HCL-specific provider requirement and, when the
    resource block needs human completion, the reason. Emitted once per policy; see
    :func:`~remgen.core.generators.common.recipe_notes` for why.
    """
    notes = recipe_notes(recipe, docs_label=docs_label)
    if recipe.hcl is None:
        return notes
    notes.append(f"Requires provider >= {recipe.hcl.min_provider_version}")
    if not recipe.hcl.is_complete:
        # Stays inline and stays explicit: a placeholder that looks like a value is
        # the one failure here that silently reconfigures a resource.
        notes.extend(
            (
                "",
                "INCOMPLETE: the provider requires "
                f"{', '.join(recipe.hcl.unresolvable_names)}, which a finding cannot "
                "supply. The TODO placeholders below satisfy type checking only -- "
                "replace each with the resource's real value, or the import will "
                "reconfigure the resource incorrectly.",
            )
        )
    return notes


def render_one(
    recipe: Recipe,
    finding: Finding,
    label: str | None = None,
    *,
    standalone: bool = True,
    docs_label: str = "Provider docs",
) -> str:
    """Render the import + resource block pair for a single finding.

    Args:
        recipe: The remediation to render.
        finding: The violation to render it against.
        label: The HCL resource label to use. Normally supplied by
            :func:`assign_labels`, which guarantees uniqueness across the whole
            file. Defaults to the resource-id-derived label, which is correct for
            a single block but *not* unique when two resources in different
            accounts or regions share a name -- so multi-finding callers must pass
            an assigned label.
        standalone: When True, prefix the full recipe description so the block is
            self-contained. :func:`render_hcl` passes False because it emits that
            description once per policy.
        docs_label: How to label the documentation link, e.g. ``"AWS docs"``.
            Only used when ``standalone`` is True.

    Raises:
        ValueError: If the recipe has no HCL target.
        TemplateError: If the recipe's templates and the finding are incompatible.
        UnsafeIdentifierError: If a finding value fails validation.
    """
    if recipe.hcl is None:
        raise ValueError(
            f"{recipe.policy_id}: no HCL target for this recipe; callers must filter "
            f"on `recipe.hcl is not None` before rendering"
        )

    target = recipe.hcl
    if label is None:
        label = to_hcl_label(finding.resource_id)
    import_id = render_template(target.import_id_template, finding)

    # Only what is specific to this resource. Everything shared -- summary, safety
    # notes, prerequisites, caveats, provider version, docs -- is emitted once per
    # policy by render_hcl, or by hcl_recipe_notes when rendering standalone.
    notes: list[str] = [finding.resource_id]
    if standalone:
        notes = hcl_recipe_notes(recipe, docs_label=docs_label) + [
            "",
            f"Resource: {finding.resource_id}",
        ]
    if not target.is_complete:
        notes.append(
            f"TODO: replace the {', '.join(target.unresolvable_names)} placeholder(s) "
            "below with this resource's real value(s) before applying."
        )

    attrs = "\n".join(_attr_lines(recipe, finding))
    return (
        f"{comment_block(notes)}\n"
        f"import {{\n"
        f"  to = {target.resource_type}.{label}\n"
        f'  id = "{import_id}"\n'
        f"}}\n"
        f"\n"
        f'resource "{target.resource_type}" "{label}" {{\n'
        f"{attrs}\n"
        f"}}\n"
    )


def render_hcl(
    pairs: list[tuple[Recipe, Finding]],
    *,
    version: str,
    generated_at: str,
    unit: OutputUnit | None = None,
    command: str = "remgen",
    docs_label: str = "Provider docs",
    scope_block: Callable[[OutputUnit], str] | None = None,
) -> str:
    """Render a complete ``.tf`` file for the given findings.

    Pairs whose recipe has no HCL target are skipped; the caller is responsible
    for reporting those so the omission is visible rather than silent.

    Args:
        pairs: ``(recipe, finding)`` pairs to render.
        version: Tool version, recorded in the header.
        generated_at: ISO-8601 timestamp, supplied so this stays deterministic.
        unit: The output unit this file covers, when the caller has split output by
            scope. Supplying it lets ``scope_block`` record the scope the provider
            must be configured for. ``None`` renders without a scope statement,
            which is only correct when every finding shares one scope.
        command: The command that produced this file, for the provenance header.
        docs_label: How to label documentation links, e.g. ``"AWS docs"``.
        scope_block: Renders the cloud's scope statement and commented ``provider``
            block for ``unit``. Supplied by the provider because the block names a
            real provider type and its credential-guard argument
            (``allowed_account_ids`` for AWS, ``subscription_id`` for Azure), which
            a generic renderer cannot know. Returning ``""`` emits no statement.
            When omitted, no scope statement is rendered -- a file that silently
            drops it is the case that gets applied against the wrong scope, so
            providers must pass one; the default exists only for unit tests that
            render a single block.
    """
    parts: list[str] = [
        _HEADER.format(
            command=command,
            project=PROJECT_NAME,
            version=version,
            generated_at=generated_at,
        )
    ]

    if unit is not None and scope_block is not None:
        parts.append(scope_block(unit))

    # Labels are assigned across the whole file, not per block: uniqueness is a
    # property of the set, so it cannot be decided one block at a time.
    labels = assign_labels(pairs)
    renderable = [(i, r, f) for i, (r, f) in enumerate(pairs) if r.hcl is not None]
    if not renderable:
        parts.append(_NO_RESULTS)
        return "".join(parts)

    # A count only -- the reason and the consequence are stated once per policy
    # below, and repeating them here made the same paragraph appear twice in every
    # file. What a reader needs at the top is how much completion work there is.
    incomplete = sum(1 for _, r, _f in renderable if not r.hcl.is_complete)
    if incomplete:
        parts.append(
            f"\n# TODO: {incomplete} of {len(renderable)} resource block(s) below need "
            f"values completed before applying.\n"
        )

    for tier in (SafetyTier.SAFEST, SafetyTier.CAUTION, SafetyTier.DISRUPTIVE):
        in_tier = [(i, r, f) for i, r, f in renderable if r.safety_tier is tier]
        if not in_tier:
            continue
        bar = "=" * 74
        parts.append(f"\n# {bar}\n# Safety tier: {tier.value.upper()}\n# {bar}\n")
        # Group by policy so each recipe's description and warnings are stated once
        # above the blocks they govern, rather than repeated on every block. Grouped
        # by (recipe, index) rather than by Finding, because two findings can be
        # equal objects and each still needs its own distinct label.
        groups: dict[str, tuple[Recipe, list[int]]] = {}
        for index, recipe, _finding in in_tier:
            entry = groups.setdefault(recipe.policy_id, (recipe, []))
            entry[1].append(index)

        by_index = {i: f for i, _r, f in in_tier}
        for recipe, group_indices in groups.values():
            notes = hcl_recipe_notes(recipe, docs_label=docs_label)
            notes.append(f"Resources below: {len(group_indices)}")
            parts.append("\n" + comment_block(notes) + "\n")
            for index in group_indices:
                parts.append(
                    "\n"
                    + render_one(
                        recipe, by_index[index], labels[index], standalone=False
                    )
                )

    return "".join(parts)


__all__ = ["assign_labels", "hcl_recipe_notes", "render_hcl", "render_one"]
