"""Generate a reviewable ``az`` CLI remediation script.

The shape follows the AWS generator -- emitted never executed, ``set -euo
pipefail``, one command per resource, safety notes as comments, one file per
credential scope -- because those decisions are about reviewability and are not
cloud-specific. See :mod:`remgen.providers.aws.shell` for the reasoning behind each.

**Where Azure differs, and why it is not a translation of the AWS script.** The AWS
guard rests on a property Azure does not have: an AWS credential set names exactly
one account, so "these credentials are for the wrong account" is a fact the script
can establish and refuse on. One ``az login`` routinely spans many subscriptions --
three on the machine this was developed against -- and ``--subscription`` is a
*global argument* accepted by every mutating command. So for Azure:

* Checking the *active* subscription and refusing on mismatch would be both
  annoying and unsafe. Annoying because the user's default is often simply a
  different one of the subscriptions they legitimately hold; unsafe because it
  implies the active subscription is what the commands will target, which is only
  true if every command omits ``--subscription``.
* Instead, **every generated command carries an explicit ``--subscription``**, and
  the guard checks that the subscription is *accessible* rather than *active*. The
  target is then a property of each command rather than of ambient state, which is
  what makes it reviewable: a reader can see which subscription each line hits
  without knowing anything about the shell it will run in.
* The preflight therefore asserts accessibility (``az account list`` filtered by
  id, which is read-only) and, separately, *reports* the active subscription
  without requiring it to match -- because a mismatch is informative but not an
  error once every command is explicit.

That last point inverts the AWS behaviour, so it is stated in the artifact itself
rather than only here: a reviewer who knows the AWS script refuses on mismatch must
not assume this one does.
"""

from __future__ import annotations

from remgen import PROJECT_NAME
from remgen.core.generators.common import (
    comment_block,
    group_by_policy,
    recipe_notes,
    render_template,
    tier_banner,
)
from remgen.core.layout import OutputUnit
from remgen.core.model import Finding, Recipe, SafetyTier

#: The command that produces these scripts, named in the provenance header so a
#: reader can regenerate the file. Hardcoded for the same reason the AWS generator
#: hardcodes its own: this module *is* the Azure shell generator, so no other
#: command can produce its output and a parameter would imply otherwise.
_COMMAND = "azremgen"


def azure_recipe_notes(recipe: Recipe, *, count: int | None = None) -> list[str]:
    """Recipe notes for Azure scripts.

    The shared :func:`~remgen.core.generators.common.recipe_notes` unchanged --
    nothing in the notes is cloud-specific, because they read only
    :class:`~remgen.core.model.Recipe` fields. Kept as a named seam for the same
    reason the AWS one is: the first genuinely Azure-specific note needs a home that
    is not the shared function, because adding a cloud's special case to ``core`` is
    how ``core`` stops being cloud-neutral.
    """
    return recipe_notes(recipe, count=count)


#: Short by design, matching the AWS header's rationale: the review checklist and the
#: explanation of how these are generated live in README.md alongside the artifacts.
#: Retained here are the things that must reach someone who opens one script in
#: isolation -- provenance, the modifies-Azure warning, and the version requirement.
_HEADER = """\
#!/usr/bin/env bash
#
# Generated by {command} ({project}) v{version}
# Generated: {generated_at}
#
# THIS SCRIPT MODIFIES AZURE RESOURCES. Review it before running it. Remediations
# come from a curated, individually verified recipe set; coverage is intentionally
# partial. See README.md in this directory for the review checklist.
#
# Requires: {cli_requirement}, and credentials that can reach the subscription below.
#
# shellcheck disable=SC2086
set -euo pipefail

if ! command -v az >/dev/null 2>&1; then
  echo "error: the 'az' CLI is not on PATH." >&2
  exit 1
fi
"""

#: Emitted when the script's scope is known.
#:
#: Deliberately **not** the AWS account guard translated. It asserts the target
#: subscription is *reachable*, not that it is *active*, because every command below
#: passes ``--subscription`` explicitly and therefore does not depend on the active
#: one. Requiring a match would reject a user whose default is a different
#: subscription they legitimately hold, while implying the ambient context is what
#: gets changed -- the opposite of what the explicit flags guarantee.
#:
#: ``az account list`` is read-only and needs no permission beyond being logged in,
#: so the check cannot fail closed for a legitimate caller. The ``--query`` filter
#: returns a count rather than the subscription object, so nothing about other
#: subscriptions is printed.
_SUBSCRIPTION_PREFLIGHT = """
# Subscription guard. Every command below names --subscription explicitly, so this
# does NOT require the subscription to be your active one -- it checks you can reach
# it at all, and fails before any change if you cannot.
#
# Note for readers familiar with the AWS script: that one refuses to run when the
# active account differs. This one does not, because an Azure login legitimately
# spans subscriptions and the target here is stated per command rather than
# inherited from the shell.
expected_subscription="{scope_id}"
if ! az account show >/dev/null 2>&1; then
  echo "error: not logged in to Azure. Run 'az login' and re-run." >&2
  exit 1
fi
reachable="$(az account list --query "length([?id=='$expected_subscription'])" --output tsv)"
if [[ "$reachable" != "1" ]]; then
  echo "error: subscription $expected_subscription is not available to these" >&2
  echo "       credentials. These remediations are for that subscription only." >&2
  echo "       Run 'az login' with an identity that can reach it, or" >&2
  echo "       'az account set --subscription $expected_subscription' if you" >&2
  echo "       expected it to be present." >&2
  exit 1
fi
active_subscription="$(az account show --query id --output tsv)"
if [[ "$active_subscription" != "$expected_subscription" ]]; then
  echo "note: your active subscription is $active_subscription, but every command"
  echo "      below targets $expected_subscription explicitly. Proceeding."
fi
echo "Subscription $expected_subscription confirmed. Scope: {scope}"
"""

_FOOTER = """
echo
echo "Done. {count} remediation command(s) completed."
echo "Re-scan in Tenable Cloud Security to confirm the findings clear."
"""


class SubscriptionNotPinnedError(ValueError):
    """Raised when a rendered ``az`` command does not name its subscription.

    The script's own header tells the reader that every command targets the
    subscription explicitly, and the preflight deliberately does *not* refuse on an
    active-subscription mismatch *because* of that promise. If a template omitted
    ``--subscription``, the command would silently inherit whichever subscription the
    shell happened to have selected -- and the guard, having been relaxed on the
    strength of the promise, would not catch it.

    So the promise is enforced where it is made rather than trusted. This is the
    failure mode of the comment that proves one component safe and says nothing about
    the others: a reader who sees "every command names --subscription" stops checking
    the commands.
    """


def _require_pinned_subscription(command: str, recipe: Recipe) -> str:
    """Return ``command`` if it pins the subscription, else raise.

    Checked on the *rendered* command rather than on the template, because a template
    could in principle build the flag from a placeholder; what has to be true is that
    the line the user runs contains it.
    """
    if "--subscription" not in command:
        raise SubscriptionNotPinnedError(
            f"recipe {recipe.policy_id} ({recipe.policy_title}) renders an az command "
            f"that does not pass --subscription:\n  {command}\n"
            f"Every generated command must name its subscription explicitly. The "
            f"script header promises this, and the subscription preflight is relaxed "
            f"on the strength of it -- an unpinned command would target whichever "
            f"subscription the caller's shell had selected. Add "
            f"'--subscription {{account_id}}' to the recipe's cli_template."
        )
    return command


def render_one(recipe: Recipe, finding: Finding, *, standalone: bool = True) -> str:
    """Render the command for a single finding.

    Args:
        recipe: The remediation to render.
        finding: The violation to render it against.
        standalone: When True, prefix the full recipe description so the block is
            self-contained. :func:`render_cli_script` passes False because it emits
            that description once per policy group.

    Raises:
        SubscriptionNotPinnedError: If the rendered command does not name its
            subscription, which would make the script header's promise false.
        TemplateError: If the recipe's template and the finding are incompatible.
        UnsafeIdentifierError: If a finding value fails validation.
    """
    command = _require_pinned_subscription(render_template(recipe.cli_template, finding), recipe)
    # Only what differs between findings of the same policy. The location is
    # included because an Azure script may span locations even though it never spans
    # subscriptions -- the same reason the AWS script includes the region.
    per_finding = comment_block([f"{finding.resource_id}  ({finding.region})"])
    echo_label = f'echo ">> {recipe.policy_title} :: {finding.resource_id}"'
    body = f"{per_finding}\n{echo_label}\n{command}\n"
    if standalone:
        return f"{comment_block(azure_recipe_notes(recipe))}\n{body}"
    return body


def render_cli_script(
    pairs: list[tuple[Recipe, Finding]],
    *,
    version: str,
    generated_at: str,
    unit: OutputUnit | None = None,
    cli_requirement: str = "Azure CLI (az) 2.50 or later",
) -> str:
    """Render a complete ``az`` remediation shell script.

    Args:
        pairs: ``(recipe, finding)`` pairs to remediate.
        version: Tool version, recorded in the header for traceability.
        generated_at: ISO-8601 timestamp, supplied by the caller so this function
            stays deterministic and unit-testable.
        unit: The output unit this script covers, when the caller has split output
            by scope. Supplying it adds the scope to the header and the subscription
            preflight. ``None`` renders an unscoped script, correct only when every
            finding is in one subscription.
        cli_requirement: What the script needs installed, named in the header.
            Defaulted rather than required so this function can be called directly
            in a test without reconstructing the provider descriptor.

    Returns:
        The script text. Contains no commands when ``pairs`` is empty, so the output
        is still a valid, safe-to-run script.
    """
    parts: list[str] = [
        _HEADER.format(
            command=_COMMAND,
            project=PROJECT_NAME,
            version=version,
            generated_at=generated_at,
            cli_requirement=cli_requirement,
        )
    ]

    if unit is not None:
        parts.append(
            "#\n"
            + comment_block(
                [
                    f"Scope: {unit.scope_description}",
                    f"Remediations in this file: {len(pairs)}",
                    "",
                    "Every command below names this subscription explicitly. The guard "
                    "below confirms you can reach it before making any change.",
                ]
            )
            + "\n"
        )

    if not pairs:
        parts.append('\necho "No remediable findings were supplied."\n')
        return "".join(parts)

    if unit is not None:
        parts.append(
            _SUBSCRIPTION_PREFLIGHT.format(scope_id=unit.scope_id, scope=unit.scope_description)
        )

    # Group by tier so the riskiest commands are never interleaved with the routine
    # ones, and a reviewer can truncate the file at a tier boundary.
    for tier in (SafetyTier.SAFEST, SafetyTier.CAUTION, SafetyTier.DISRUPTIVE):
        in_tier = [(r, f) for r, f in pairs if r.safety_tier is tier]
        if not in_tier:
            continue
        parts.append(f"\n{tier_banner(tier)}\n")
        # Then group by policy, so each policy's description and safety notes are
        # stated once above the commands they apply to.
        for recipe, findings in group_by_policy(in_tier):
            parts.append(
                "\n" + comment_block(azure_recipe_notes(recipe, count=len(findings))) + "\n"
            )
            for finding in findings:
                parts.append("\n" + render_one(recipe, finding, standalone=False))

    parts.append(_FOOTER.format(count=len(pairs)))
    return "".join(parts)


__all__ = ["azure_recipe_notes", "render_cli_script", "render_one"]
