"""Generate a reviewable ``aws`` CLI remediation script.

Design decisions worth stating, because each is a deliberate trade-off:

* **The script is emitted, never executed.** This module returns a string. The
  user reads it, then runs it themselves. That is the whole safety model.
* **``set -euo pipefail``** so a failure stops the run instead of continuing
  through the rest of an estate with a broken assumption.
* **One command per resource, not a loop.** Verbose, but every line is
  independently readable, greppable and removable. A reviewer can delete the
  three resources they disagree with and run the rest.
* **Safety notes are rendered as comments in the artifact**, derived from the
  recipe's structured fields, so the warning travels with the file rather than
  living only in a terminal summary the user has already scrolled past.
* **Shared prose is stated once per policy, not once per resource.** The summary,
  safety notes, prerequisites, caveats and documentation link are properties of the
  recipe, so repeating them above every command made comments ~85% of the file and
  buried the commands. They are now a section header above the group of resources
  they govern; each command keeps only what is specific to its resource. Same
  information, read once instead of a thousand times.
* **One script per AWS account.** The script uses the caller's ambient
  credentials, so a script spanning accounts cannot be run. When the caller
  supplies a scope, the script asserts the credentials match the intended account
  before changing anything -- see :mod:`remgen.core.layout`.
"""

from __future__ import annotations

from remgen import PROJECT_NAME
from remgen.core.generators.common import (
    comment_block,
    group_by_policy,
    recipe_notes,
    render_template,
    tier_banner,
)
from remgen.core.layout import OutputUnit
from remgen.core.model import Finding, Recipe, SafetyTier

#: The command that produces these scripts, named in the provenance header so a
#: reader can regenerate the file. Hardcoded rather than threaded through from the
#: Provider: this module *is* the AWS shell generator, so there is no other command
#: that can produce its output, and a parameter would imply otherwise.
_COMMAND = "awsremgen"


def aws_recipe_notes(recipe: Recipe, *, count: int | None = None) -> list[str]:
    """Recipe notes for AWS scripts.

    Currently the shared :func:`~remgen.core.generators.common.recipe_notes`
    unchanged: nothing in the notes is AWS-specific, because they read only
    :class:`~remgen.core.model.Recipe` fields. Kept as a named seam anyway, so that
    the first genuinely AWS-specific note has an obvious home that is not the shared
    function -- adding a cloud's special case to `core` is how `core` stops being
    cloud-neutral.
    """
    return recipe_notes(recipe, count=count)


#: Short by design. The review checklist and the explanation of how these are
#: generated live in README.md alongside the artifacts, written once per run rather
#: than repeated in every per-account script. Retained here: provenance, the
#: modifies-AWS warning, and the version requirement -- the things that must reach
#: someone who opens one script in isolation.
_HEADER = """\
#!/usr/bin/env bash
#
# Generated by {command} ({project}) v{version}
# Generated: {generated_at}
#
# THIS SCRIPT MODIFIES AWS RESOURCES. Review it before running it. Remediations
# come from a curated, individually verified recipe set; coverage is intentionally
# partial. See README.md in this directory for the review checklist.
#
# Requires: AWS CLI v2 (v1 is not tested) and credentials for the account below.
#
# shellcheck disable=SC2086
set -euo pipefail

if ! command -v aws >/dev/null 2>&1; then
  echo "error: the 'aws' CLI is not on PATH." >&2
  exit 1
fi
"""

#: Emitted when the script's scope is known. Turns "ran against the wrong
#: account" from a silent partial change into a refusal before the first write.
#: ``sts get-caller-identity`` is read-only and needs no permission beyond being
#: authenticated, so the check itself cannot fail closed for a legitimate caller.
_ACCOUNT_PREFLIGHT = """
# Account guard. This script uses whatever credentials your shell provides and
# cannot switch between them, so it targets one account and refuses to run against
# any other rather than changing the wrong resources.
expected_account="{account_id}"
actual_account="$(aws sts get-caller-identity --query Account --output text)"
if [[ "$actual_account" != "$expected_account" ]]; then
  echo "error: these remediations are for account $expected_account," >&2
  echo "       but your credentials are for account $actual_account." >&2
  echo "       Select the right profile (AWS_PROFILE / --profile) and re-run." >&2
  exit 1
fi
echo "Account $expected_account confirmed. Scope: {scope}"
"""

_FOOTER = """
echo
echo "Done. {count} remediation command(s) completed."
echo "Re-scan in Tenable Cloud Security to confirm the findings clear."
"""


def render_one(recipe: Recipe, finding: Finding, *, standalone: bool = True) -> str:
    """Render the command for a single finding.

    Args:
        recipe: The remediation to render.
        finding: The violation to render it against.
        standalone: When True, prefix the full recipe description, so the block is
            self-contained. :func:`render_cli_script` passes False because it emits
            that description once for the whole group -- repeating it per resource is
            what made comments the bulk of the file.

    Raises:
        TemplateError: If the recipe's template and the finding are incompatible.
        UnsafeIdentifierError: If a finding value fails validation.
    """
    command = render_template(recipe.cli_template, finding)
    # Only what differs between findings of the same policy. Region is included
    # because a script may span regions even though it never spans accounts.
    per_finding = comment_block([f"{finding.resource_id}  ({finding.region})"])
    echo_label = f'echo ">> {recipe.policy_title} :: {finding.resource_id}"'
    body = f"{per_finding}\n{echo_label}\n{command}\n"
    if standalone:
        return f"{comment_block(aws_recipe_notes(recipe))}\n{body}"
    return body


def render_cli_script(
    pairs: list[tuple[Recipe, Finding]],
    *,
    version: str,
    generated_at: str,
    unit: OutputUnit | None = None,
) -> str:
    """Render a complete remediation shell script.

    Args:
        pairs: ``(recipe, finding)`` pairs to remediate.
        version: Tool version, recorded in the header for traceability.
        generated_at: ISO-8601 timestamp, supplied by the caller so this
            function stays deterministic and unit-testable.
        unit: The output unit this script covers, when the caller has split output
            by scope. Supplying it adds the scope to the header and a preflight
            check that refuses to run under credentials for another account.
            ``None`` renders an unscoped script, which is correct only when every
            finding is in one account.

    Returns:
        The script text. Contains no commands when ``pairs`` is empty, so the
        output is still a valid, safe-to-run script.
    """
    parts: list[str] = [
        _HEADER.format(
            command=_COMMAND,
            project=PROJECT_NAME,
            version=version,
            generated_at=generated_at,
        )
    ]

    if unit is not None:
        parts.append(
            "#\n"
            + comment_block(
                [
                    f"Scope: {unit.scope_description}",
                    f"Remediations in this file: {len(pairs)}",
                    "",
                    "Run this file with credentials for the account named above. The "
                    "guard below verifies that before making any change.",
                ]
            )
            + "\n"
        )

    if not pairs:
        parts.append('\necho "No remediable findings were supplied."\n')
        return "".join(parts)

    if unit is not None:
        parts.append(
            _ACCOUNT_PREFLIGHT.format(account_id=unit.scope_id, scope=unit.scope_description)
        )

    # Group by tier so the riskiest commands are never interleaved with the
    # routine ones, and a reviewer can truncate the file at a tier boundary.
    for tier in (SafetyTier.SAFEST, SafetyTier.CAUTION, SafetyTier.DISRUPTIVE):
        in_tier = [(r, f) for r, f in pairs if r.safety_tier is tier]
        if not in_tier:
            continue
        parts.append(f"\n{tier_banner(tier)}\n")
        # Then group by policy, so each policy's description, safety notes and
        # caveats are stated once above the commands they apply to.
        for recipe, findings in group_by_policy(in_tier):
            parts.append("\n" + comment_block(aws_recipe_notes(recipe, count=len(findings))) + "\n")
            for finding in findings:
                parts.append("\n" + render_one(recipe, finding, standalone=False))

    parts.append(_FOOTER.format(count=len(pairs)))
    return "".join(parts)


__all__ = ["aws_recipe_notes", "render_cli_script", "render_one"]
